// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/go@4.0.0-preview.74)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package aisearch

import (
	"context"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/policy"
	"github.com/Azure/azure-sdk-for-go/sdk/azcore/runtime"
	"net/http"
)

// SearchServiceClient contains the methods for the SearchServiceClient group.
// Don't use this type directly, use a constructor function instead.
type SearchServiceClient struct {
	internal *azcore.Client
	endpoint string
}

// GetServiceStatistics - Gets service level statistics for a search service.
// If the operation fails it returns an *azcore.ResponseError type.
//
// Generated from API version 2025-09-01
//   - RequestOptions - RequestOptions contains a group of parameters for the DataSourcesClient.CreateOrUpdate method.
//   - options - SearchServiceClientGetServiceStatisticsOptions contains the optional parameters for the SearchServiceClient.GetServiceStatistics
//     method.
func (client *SearchServiceClient) GetServiceStatistics(ctx context.Context, requestOptions *RequestOptions, options *SearchServiceClientGetServiceStatisticsOptions) (SearchServiceClientGetServiceStatisticsResponse, error) {
	var err error
	req, err := client.getServiceStatisticsCreateRequest(ctx, requestOptions, options)
	if err != nil {
		return SearchServiceClientGetServiceStatisticsResponse{}, err
	}
	httpResp, err := client.internal.Pipeline().Do(req)
	if err != nil {
		return SearchServiceClientGetServiceStatisticsResponse{}, err
	}
	if !runtime.HasStatusCode(httpResp, http.StatusOK) {
		err = runtime.NewResponseError(httpResp)
		return SearchServiceClientGetServiceStatisticsResponse{}, err
	}
	resp, err := client.getServiceStatisticsHandleResponse(httpResp)
	return resp, err
}

// getServiceStatisticsCreateRequest creates the GetServiceStatistics request.
func (client *SearchServiceClient) getServiceStatisticsCreateRequest(ctx context.Context, requestOptions *RequestOptions, _ *SearchServiceClientGetServiceStatisticsOptions) (*policy.Request, error) {
	urlPath := "/servicestats"
	req, err := runtime.NewRequest(ctx, http.MethodGet, runtime.JoinPaths(client.endpoint, urlPath))
	if err != nil {
		return nil, err
	}
	reqQP := req.Raw().URL.Query()
	reqQP.Set("api-version", "2025-09-01")
	req.Raw().URL.RawQuery = reqQP.Encode()
	req.Raw().Header["Accept"] = []string{"application/json"}
	if requestOptions != nil && requestOptions.XMSClientRequestID != nil {
		req.Raw().Header["x-ms-client-request-id"] = []string{*requestOptions.XMSClientRequestID}
	}
	return req, nil
}

// getServiceStatisticsHandleResponse handles the GetServiceStatistics response.
func (client *SearchServiceClient) getServiceStatisticsHandleResponse(resp *http.Response) (SearchServiceClientGetServiceStatisticsResponse, error) {
	result := SearchServiceClientGetServiceStatisticsResponse{}
	if err := runtime.UnmarshalAsJSON(resp, &result.ServiceStatistics); err != nil {
		return SearchServiceClientGetServiceStatisticsResponse{}, err
	}
	return result, nil
}

