// Code generated by Microsoft (R) AutoRest Code Generator (autorest: 3.10.8, generator: @autorest/go@4.0.0-preview.74)
// Changes may cause incorrect behavior and will be lost if the code is regenerated.
// Code generated by @autorest/go. DO NOT EDIT.

package aisearchindex

// VectorQueryClassification provides polymorphic access to related types.
// Call the interface's GetVectorQuery() method to access the common type.
// Use a type switch to determine the concrete type.  The possible types are:
// - *VectorQuery, *VectorizableTextQuery, *VectorizedQuery
type VectorQueryClassification interface {
	// GetVectorQuery returns the VectorQuery content of the underlying type.
	GetVectorQuery() *VectorQuery
}

